'use client';
import {useState,useEffect,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowRight,MapPin,ArrowUpRight,LoaderCircle} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {families,products,familyProducts} from '@/data/products';
import {site} from '@/data/site';
import {MagneticButton,SectionLabel,Arrow} from './shared';
type Store={name:string;address:string;url?:string;};
export function StoreLocator({full=false}:{full?:boolean}){const [cep,setCep]=useState('');const [state,setState]=useState<'idle'|'loading'|'success'|'empty'|'error'>('idle');const [message,setMessage]=useState('');const [stores,setStores]=useState<Store[]>([]);const [selected,setSelected]=useState('');
 useEffect(()=>{const slug=new URLSearchParams(location.search).get('produto');const p=products.find(p=>p.slug===slug);if(p)setSelected(p.name+' · '+p.flavor);},[]);
 async function submit(e:FormEvent){e.preventDefault();const value=cep.replace(/\D/g,'');if(value.length!==8){setState('error');setMessage('Informe um CEP válido com 8 dígitos.');return;}setState('loading');setMessage('Buscando pontos de venda…');try{const r=await fetch('/api/revendedores?cep='+value);const d=await r.json() as {message?:string;stores?:Store[]};if(!r.ok)throw new Error(d.message||'Não foi possível consultar agora.');const list=Array.isArray(d.stores)?d.stores:[];setStores(list);setState(list.length?'success':'empty');setMessage(list.length?`${list.length} ponto(s) de venda encontrado(s).`:'Ainda não encontramos revendedores para esse CEP. Consulte os canais online.');}catch(e){setState('error');setMessage(e instanceof Error?e.message:'Tente novamente em instantes.');}}
 return <section className={`store-locator section-pad ${full?'store-full':''}`} id="onde-comprar"><SectionLabel index="08">O próximo movimento é seu.</SectionLabel><div className="store-main"><div><h2 className="display">SUA PRÓXIMA<br/>MOVING ESTÁ<br/><span>LOGO ALI.</span></h2><p>Sua próxima Moving está mais perto<br/>do que você imagina.</p>{selected&&<p className="selected-product">Você escolheu: {selected}</p>}<MagneticButton href={full?'#canais':'/onde-comprar#canais'}>Comprar online</MagneticButton></div><div className="store-search"><div className="store-symbol" aria-hidden="true"><MapPin size={56} strokeWidth={1.2}/></div><h3>Encontre Moving perto de você.</h3><p>Qual é o seu CEP?</p><form onSubmit={submit} noValidate><label className="sr-only" htmlFor="cep">CEP</label><div className="input-row"><input id="cep" inputMode="numeric" autoComplete="postal-code" placeholder="00000-000" value={cep} maxLength={9} aria-invalid={state==='error'} aria-describedby="cep-feedback" onChange={e=>{const n=e.target.value.replace(/\D/g,'').slice(0,8);setCep(n.length>5?n.slice(0,5)+'-'+n.slice(5):n);if(state!=='idle')setState('idle');}}/><button type="submit" aria-label="Encontrar revendedores" disabled={state==='loading'}>{state==='loading'?<LoaderCircle className="spin"/>:<ArrowRight/>}</button></div><button type="submit" className="text-link" disabled={state==='loading'}>Encontrar revendedores <Arrow/></button><p id="cep-feedback" className={`form-feedback ${state}`} role="status" aria-live="polite">{message||'Prefere falar com a gente? sac@movingpro.com.br'}</p></form>{stores.length>0&&state==='success'&&<ul className="store-results">{stores.map((s,i)=><li key={i}><strong>{s.name}</strong><span>{s.address}</span>{s.url&&/^https:\/\//.test(s.url)&&<a href={s.url} target="_blank" rel="noopener noreferrer">Ver ponto de venda <Arrow/></a>}</li>)}</ul>}</div></div>{full&&<div className="store-channels" id="canais"><h3 className="display">ENCONTRE SUA MOVING ONLINE.</h3><p>Selecione uma linha para consultar os produtos e os links publicados pela marca. Preços e disponibilidade são informados pelo canal de venda.</p><div>{families.map(f=>{const p=familyProducts(f.id).find(p=>p.buyUrl);return <article key={f.id}><span>{f.short}</span>{p?<a href={p.buyUrl!} target="_blank" rel="noopener noreferrer">Mercado Livre <Arrow/></a>:<Link href="/contato">Consultar a Moving <Arrow/></Link>}<Link href={'/produtos?linha='+f.id}>Escolher sabor</Link></article>;})}</div><p className="small-note">É revendedor? <a href={'mailto:'+site.email}>Fale com a Moving</a>.</p></div>}</section>;
}
export function Newsletter(){const [email,setEmail]=useState('');const [consent,setConsent]=useState(false);const [status,setStatus]=useState('idle');const [message,setMessage]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setStatus('error');setMessage('Digite um e-mail válido para continuar.');return;}if(!consent){setStatus('error');setMessage('Confirme que deseja receber novidades da Moving.');return;}setStatus('loading');setMessage('Enviando…');try{const r=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,consent})});const d=await r.json() as {message?:string;stores?:Store[]};if(!r.ok)throw new Error(d.message||"Não foi possível concluir o envio.");setStatus('success');setMessage('Você entrou no ritmo! Inscrição recebida.');setEmail('');}catch(e){setStatus('error');setMessage(e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.');}}
 return <section className="newsletter section-pad" id="newsletter"><div><SectionLabel index="09">Novidades que valem o seu tempo.</SectionLabel><h2 className="display">DÊ UM BOOST<br/>NA SUA CAIXA<br/>DE ENTRADA.</h2></div><form onSubmit={submit} noValidate><p>Lançamentos, sabores e boas doses de movimento.</p><label htmlFor="newsletter-email">Seu e-mail</label><div className={`input-row ${status==='loading'?'submitting':''}`}><input id="newsletter-email" type="email" autoComplete="email" placeholder="voce@exemplo.com" value={email} onChange={e=>setEmail(e.target.value)} aria-invalid={status==='error'} aria-describedby="newsletter-feedback" required/><button disabled={status==='loading'} type="submit" aria-label="Quero receber">{status==='loading'?<LoaderCircle className="spin"/>:<ArrowUpRight/>}</button></div><label className="consent" htmlFor="newsletter-consent"><Checkbox id="newsletter-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>Quero receber novidades e li a <Link href="/politicas-de-privacidade">Política de Privacidade</Link>.</span></label><button className="text-link" type="submit" disabled={status==='loading'}>Quero receber <Arrow/></button><p id="newsletter-feedback" className={`form-feedback ${status}`} role="status" aria-live="polite">{message}</p></form></section>;
}
export function ContactForm(){const [status,setStatus]=useState('idle');const [message,setMessage]=useState('');const [consent,setConsent]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;if(!consent){setStatus('error');setMessage('Confirme a leitura da Política de Privacidade.');return;}setStatus('loading');try{const data=Object.fromEntries(new FormData(form));const r=await fetch('/api/contato',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,consent})});const d=await r.json() as {message?:string;stores?:Store[]};if(!r.ok)throw new Error(d.message||"Não foi possível concluir o envio.");setStatus('success');setMessage('Mensagem recebida. Obrigado por falar com a Moving.');form.reset();setConsent(false);}catch(e){setStatus('error');setMessage(e instanceof Error?e.message:'Não foi possível enviar sua mensagem.');}}
 return <form className="contact-form" onSubmit={submit}><label htmlFor="contact-name">Seu nome</label><input id="contact-name" name="name" autoComplete="name" required minLength={2} maxLength={120}/><label htmlFor="contact-email">Seu e-mail</label><input id="contact-email" name="email" type="email" autoComplete="email" required maxLength={254}/><label htmlFor="contact-message">Como podemos ajudar?</label><textarea id="contact-message" name="message" rows={5} required minLength={10} maxLength={5000}/><label className="consent" htmlFor="contact-consent"><Checkbox id="contact-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>Li a <Link href="/politicas-de-privacidade">Política de Privacidade</Link> e concordo com o uso dos dados para responder à mensagem.</span></label><button className="pill" disabled={status==='loading'}>{status==='loading'?'Enviando…':'Enviar mensagem'}<Arrow/></button><p className={`form-feedback ${status}`} role="status">{message}</p></form>;
}
