'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Plus} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {families,products,type Product} from '@/data/products';
import {MagneticButton,ProductImage,SectionLabel,Arrow,ColorStyle} from './shared';
import {site} from '@/data/site';
import {registerCatalogTool} from '@/lib/webmcp';
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <div className="catalog-filter"><span id={'filter-'+label}>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={'filter-'+label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
export function ProductCard({product:p}:{product:Product}){return <article className="product-card" style={ColorStyle(p.color)}><Link className="product-card-art" href={'/produtos/'+p.slug}><span className="product-format mono">{p.format} / {p.amount}</span><ProductImage product={p}/><span className="product-plus"><Plus size={20}/></span></Link><div className="product-card-info"><span className="eyebrow">{p.protein} DE PROTEÍNA</span><h3><Link href={'/produtos/'+p.slug}>{p.name}</Link></h3><p>{p.flavor}</p><div><Link className="text-link" href={'/produtos/'+p.slug}>Ver produto <Arrow/></Link><a className="product-buy" href={p.buyUrl||'/onde-comprar?produto='+p.slug} target={p.buyUrl?'_blank':undefined} rel={p.buyUrl?'noopener noreferrer':undefined}>Comprar <Arrow/></a></div></div></article>;}
export function ProductRail({full=false}:{full?:boolean}){const [line,setLine]=useState('all');const [goal,setGoal]=useState('all');const [flavor,setFlavor]=useState('all');const [format,setFormat]=useState('all');const rail=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(full){const q=new URLSearchParams(location.search);setLine(q.get('linha')||'all');setGoal(q.get('objetivo')||'all');setFlavor(q.get('sabor')||'all');setFormat(q.get('formato')||'all');}},[full]);
 function change(set:(s:string)=>void,key:string,v:string){set(v);if(full){const u=new URL(location.href);v==='all'?u.searchParams.delete(key):u.searchParams.set(key,v);history.replaceState({},'',u);}}
 useEffect(()=>registerCatalogTool(v=>{setLine(v);setGoal('all');setFlavor('all');setFormat('all');if(full){const u=new URL(location.href);u.search='';if(v!=='all')u.searchParams.set('linha',v);history.replaceState({},'',u);}},v=>({line:v,products:products.filter(p=>v==='all'||p.familyId===v).map(p=>({name:p.name,flavor:p.flavor,slug:p.slug}))})),[full]);
 const filtered=products.filter(p=>(line==='all'||p.familyId===line)&&(goal==='all'||p.familyId===goal)&&(flavor==='all'||p.flavor===flavor)&&(format==='all'||p.format===format));
 const reset=()=>{setLine('all');setGoal('all');setFlavor('all');setFormat('all');if(full)history.replaceState({},'',location.pathname);};
 return <section className={`catalog section-pad ${full?'catalog-full':''}`} id="catalogo"><SectionLabel index="04">Sua próxima favorita está aqui.</SectionLabel><div className="section-heading"><h2 className="display">NOSSOS<br/>PRODUTOS.</h2>{!full&&<MagneticButton href="/produtos">Explorar todos</MagneticButton>}</div><div className="catalog-filters"><Filter label="Linha" value={line} onChange={v=>change(setLine,'linha',v)} options={families.map(f=>({value:f.id,label:f.short}))}/><Filter label="Objetivo" value={goal} onChange={v=>change(setGoal,'objetivo',v)} options={families.map(f=>({value:f.id,label:f.rhythm}))}/><Filter label="Sabor" value={flavor} onChange={v=>change(setFlavor,'sabor',v)} options={[...new Set(products.map(p=>p.flavor))].map(v=>({value:v,label:v}))}/><Filter label="Formato" value={format} onChange={v=>change(setFormat,'formato',v)} options={['Sachê','Garrafa','Lata'].map(v=>({value:v,label:v}))}/><button className="text-link filter-reset" onClick={reset}>Limpar filtros</button></div><div className="catalog-meta"><span aria-live="polite">{filtered.length} produtos no seu ritmo</span>{!full&&<div><button className="icon-button" aria-label="Produtos anteriores" onClick={()=>rail.current?.scrollBy({left:-700,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowLeft/></button><button className="icon-button" aria-label="Mais produtos" onClick={()=>rail.current?.scrollBy({left:700,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowRight/></button></div>}</div>{filtered.length?<div ref={rail} className={full?'product-grid':'product-rail'}>{filtered.map(p=><ProductCard key={p.slug} product={p}/>)}</div>:<div className="empty-state"><h3>Vamos encontrar outro ritmo?</h3><p>Nenhum produto corresponde a essa combinação.</p><button className="pill" onClick={reset}>Limpar filtros <ArrowRight/></button></div>}</section>;
}
export function AboutPreview(){return <section className="about-preview section-pad" id="a-moving"><SectionLabel index="06">Muito prazer. Somos Moving.</SectionLabel><div className="about-columns"><h2 className="display">A VIDA NÃO PARA.<br/>A GENTE<br/><span>TAMBÉM NÃO.</span></h2><div><p className="about-lead">Um novo jeito de consumir proteína: leve, refrescante e feito para acompanhar a vida real.</p><p>A Moving nasceu para tornar a proteína mais prática, mais prazerosa e mais presente na rotina. Nutrição, sabor e movimento fazem parte da mesma história.</p><MagneticButton href="/a-moving">Conheça a Moving</MagneticButton></div></div></section>;}
export function SocialWall(){return <section className="social-wall section-pad" id="comunidade"><div className="section-heading"><div><SectionLabel>Gente real. Movimento de verdade.</SectionLabel><h2 className="display">É SOBRE<br/>ESTAR JUNTO.</h2></div><a className="text-link" href={site.social[0].url} target="_blank" rel="noopener noreferrer">@moving_oficial <Arrow/></a></div><div className="social-mosaic"><a href={site.socialPosts.event} target="_blank" rel="noopener noreferrer" className="social-photo social-event"><img src="/assets/moving/social/FEED-copiar22.webp" alt="Comunidade Moving reunida em evento da marca" width="819" height="1024" loading="lazy"/><span>JUNTOS, EM MOVIMENTO <Arrow/></span></a><div className="social-quote"><span className="eyebrow">#MOVING</span><p className="display">SABOR<br/>DE BONS<br/>MOMENTOS.</p><a className="text-link" href={site.social[1].url} target="_blank" rel="noopener noreferrer">Moving no TikTok <Arrow/></a></div><a href={site.socialPosts.powder} className="social-photo" target="_blank" rel="noopener noreferrer"><img src="/assets/moving/social/FEED-copiarsache.webp" alt="Hydro PRO em pó sabor tangerina em uma composição com frutas" width="819" height="1024" loading="lazy"/><span>VAI COM VOCÊ <Arrow/></span></a></div></section>;}
