'use client';
import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Menu,X,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger,DialogClose} from '@/components/ui/dialog';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {families,familyProducts,type Product} from '@/data/products';
import {site,faqs} from '@/data/site';
export function Logo({light=false}:{light?:boolean}){return <img className={light?'logo logo-light':'logo'} src="/assets/moving/logo/moving.svg" width="800" height="228" alt="Moving"/>;}
export function Arrow(){return <ArrowUpRight size={19} aria-hidden="true"/>;}
export function MagneticButton({href,children,light=false,className=''}:{href:string;children:ReactNode;light?:boolean;className?:string}){
 const ref=useRef<HTMLAnchorElement>(null);const external=href.startsWith('http');
 return <Link ref={ref} href={href} className={`pill ${light?'pill-light':''} ${className}`} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined} onPointerMove={e=>{if(e.pointerType==='mouse'&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.06}px,${(e.clientY-r.top-r.height/2)*.1}px)`;}}} onPointerLeave={()=>{if(ref.current)ref.current.style.transform='';}}>{children}<Arrow/></Link>;
}
export function ProductImage({product,className='',priority=false}:{product:Product;className?:string;priority?:boolean}){return <img className={`packshot ${className}`} src={product.image} alt={`${product.name}, ${product.flavor}, ${product.amount}`} width="300" height="1000" loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async" draggable={false}/>;}
export function BuyButton({product}:{product:Product}){return <MagneticButton href={product.buyUrl||'/onde-comprar?produto='+product.slug}>{product.buyUrl?'Comprar':'Onde comprar'}</MagneticButton>;}
export function SectionLabel({children,index}:{children:ReactNode;index?:string}){return <div className="section-label"><span>{children}</span>{index&&<span>{index} / MOVING</span>}</div>;}
export function MovingFlow({color='#FF6B22',className=''}:{color?:string;className?:string}){return <svg className={`moving-flow ${className}`} viewBox="0 0 1440 230" fill="none" preserveAspectRatio="none" aria-hidden="true"><path d="M-90 150C160-50 300 270 610 110S1110 220 1530 50" stroke={color} strokeWidth="64"/></svg>;}
const nav=[['Produtos','/produtos'],['Qual é o seu ritmo?','/#ritmos'],['A Moving','/a-moving'],['Conteúdos','/blog'],['Onde comprar','/onde-comprar']];
export function Header(){const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);const [mega,setMega]=useState(false);const path=usePathname();
 useEffect(()=>{const scroll=()=>setScrolled(scrollY>40);scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll);},[]);
 useEffect(()=>{setOpen(false);setMega(false);},[path]);
 return <><a href="#main" className="skip-link">Pular para o conteúdo</a><header className={`site-header ${scrolled?'solid':''} ${path==='/'?'home-header':''}`}><Link href="/" aria-label="Moving — início"><Logo/></Link><nav className="desktop-nav" aria-label="Navegação principal">{nav.map(([label,href],i)=>i===0?<div className="mega-parent" key={href} onMouseEnter={()=>setMega(true)} onMouseLeave={()=>setMega(false)} onKeyDown={e=>{if(e.key==='Escape')setMega(false);}}><Link href={href} aria-current={path===href?'page':undefined}>{label}</Link><button className="mega-toggle" aria-expanded={mega} aria-controls="product-menu" aria-label="Mostrar linhas de produtos" onClick={()=>setMega(!mega)}><Plus size={13}/></button>{mega&&<div id="product-menu" className="mega-menu">{families.map(f=><Link key={f.id} href={'/produtos?linha='+f.id} onClick={()=>setMega(false)}><ProductImage product={familyProducts(f.id)[0]}/><span>{f.short}</span><small>{f.rhythm}</small></Link>)}</div>}</div>:<Link href={href} key={href} aria-current={path===href?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><MagneticButton href="/onde-comprar">Comprar</MagneticButton><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="menu-trigger icon-button" aria-label="Abrir menu"><Menu/></button></DialogTrigger><DialogContent className="fullscreen-menu" showCloseButton={false}><div className="menu-top"><Logo/><DialogClose asChild><button className="icon-button" aria-label="Fechar menu"><X/></button></DialogClose></div><DialogTitle className="sr-only">Menu Moving</DialogTitle><DialogDescription className="eyebrow">Entre no seu ritmo.</DialogDescription><nav aria-label="Navegação do menu">{nav.map(([label,href],i)=><Link href={href} key={href} onClick={()=>setOpen(false)}><small>0{i+1}</small>{label}<Arrow/></Link>)}</nav><div className="mobile-family-links">{families.map(f=><Link key={f.id} href={'/produtos?linha='+f.id} onClick={()=>setOpen(false)}>{f.rhythm}<span>{f.short}</span></Link>)}</div></DialogContent></Dialog></div></header></>;
}
export function FAQAccordion({compact=false}:{compact?:boolean}){return <section className="faq-section section-pad" id="duvidas"><div><SectionLabel index="10">Pode perguntar.</SectionLabel><h2 className="display">SEM DÚVIDAS.<br/>SÓ MOVIMENTO.</h2><p>Um pouco mais sobre o que vai com você.</p><Link className="text-link" href="/contato">Fale com a Moving <Arrow/></Link></div><Accordion type="single" collapsible className="faq-list">{(compact?faqs.slice(0,5):faqs).map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>;}
export function Footer(){return <footer className="site-footer"><div className="footer-top"><p className="eyebrow">Cada dia, um novo ritmo.</p><Link href="/produtos" className="footer-cta display">CONTINUE EM<br/>MOVIMENTO <ArrowUpRight aria-hidden="true"/></Link></div><div className="footer-links"><div><Logo light/><p>Proteína, hidratação e sabor.<br/>No ritmo da vida real.</p></div><div><span className="eyebrow">Explore</span>{[['Produtos','/produtos'],['A Moving','/a-moving'],['Quem somos','/quem-somos'],['Blog','/blog'],['Contato','/contato'],['Onde comprar','/onde-comprar']].map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><span className="eyebrow">Informações</span>{[['Política de privacidade','/politicas-de-privacidade'],['Política de cookies','/politicas-de-cookies'],['Como comprar','/como-comprar']].map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><span className="eyebrow">Entre no movimento</span>{site.social.map(s=><a href={s.url} key={s.name} target="_blank" rel="noopener noreferrer">{s.name} <Arrow/></a>)}</div></div><div className="footer-legal"><span>© {new Date().getFullYear()} Moving · CNPJ {site.cnpj}</span><span>{site.address}</span></div><div className="footer-word" aria-hidden="true">MOVING</div></footer>;}
export function ColorStyle(color:string):CSSProperties{return {'--flavor':color} as CSSProperties;}
