import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {StoreLocator,ContactForm,Newsletter} from '@/components/moving/conversion';
import {MagneticButton,SectionLabel,Arrow} from '@/components/moving/shared';
import {site} from '@/data/site';
const pages:Record<string,{title:string;description:string}>={
 'a-moving':{title:'A Moving',description:'Nutrição, praticidade e sabor para acompanhar a vida real.'},
 'quem-somos':{title:'Quem somos',description:'Conheça a origem, o propósito e a comunidade da Moving.'},
 'contato':{title:'Contato',description:'Converse com a Moving. Dúvidas sobre produtos, pontos de venda e parcerias.'},
 'onde-comprar':{title:'Onde comprar',description:'Encontre Moving online e consulte os canais oficiais de compra.'},
 'politicas-de-privacidade':{title:'Política de privacidade',description:'Informações sobre privacidade e contato com a Moving.'},
 'politicas-de-cookies':{title:'Política de cookies',description:'Informações sobre cookies e preferências nesta experiência Moving.'},
 'como-comprar':{title:'Como comprar',description:'Saiba como encontrar e comprar produtos Moving pelos canais oficiais.'},
};
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.title,description:p.description,alternates:{canonical:'/'+slug},openGraph:{title:p.title+' | Moving',description:p.description}}:{title:'Página não encontrada'};}
export default async function Page({params}:Props){const {slug}=await params;const p=pages[slug];if(!p)notFound();if(slug==='onde-comprar')return <main id="main" className="page-enter"><h1 className="sr-only">Onde comprar Moving</h1><StoreLocator full/></main>;
 if(slug==='a-moving'||slug==='quem-somos'){const who=slug==='quem-somos';return <main id="main" className="page-enter"><section className="internal-hero"><span className="eyebrow">{who?'Quem somos':'Muito prazer. Somos Moving.'}</span><h1 className="display">{who?<>SEU NOVO JEITO<br/>DE TOMAR PROTEÍNA.</>:<>O MOVIMENTO É<br/>NOSSO COMBUSTÍVEL.</>}</h1><p>Leveza, refrescância e praticidade para acompanhar os seus dias.</p></section><img className="institutional-banner" src={who?'/assets/moving/social/FEED-copiar23411s.webp':'/assets/moving/lifestyle/hydrow234w.webp'} alt={who?'Pessoa com diferentes sabores de Hydro Protein Moving':'Hydro Protein PRO em movimento sob o céu azul'} width="1400" height="700"/><section className="section-pad"><div className="institutional-body"><h2 className="display">{who?'A GENTE NASCEU PARA MOVIMENTAR.':'A VIDA MUDA. O RITMO TAMBÉM.'}</h2><div><p>{who?'A Moving nasceu da inquietação e da vontade de criar um jeito diferente de consumir proteína: mais leve, refrescante e fácil de levar para qualquer lugar.':'Fundada em 2023, a Moving nasceu com o propósito de transformar a forma como a proteína é consumida no Brasil.'}</p><p>Desenvolvemos bebidas proteicas leves, refrescantes e com sabor de frutas, criadas para se adaptar ao ritmo das pessoas.</p><p>Para a Moving, movimento vai além da atividade física. É a vontade de evoluir todos os dias, transformar hábitos e encontrar novas formas de viver com energia, leveza e liberdade.</p><MagneticButton href="/produtos">Encontre sua Moving</MagneticButton></div></div><div className="institutional-values">{[['01','NUTRIÇÃO','Bebidas funcionais que unem praticidade, sabor e desenvolvimento de produtos para acompanhar a alimentação no dia a dia.'],['02','VIDA REAL','Hábitos são construídos nas pequenas escolhas. A Moving cria soluções que se adaptam a diferentes rotinas.'],['03','MOVERS','Uma comunidade de pessoas que compartilham o amor por estar em movimento. No esporte, no trabalho e nos bons momentos.']].map(([n,t,d])=><div key={n}><span className="mono">{n}</span><h3 className="display">{t}</h3><p>{d}</p></div>)}</div></section><Newsletter/></main>;}
 if(slug==='contato')return <main id="main" className="page-enter"><section className="internal-hero"><span className="eyebrow">Vamos conversar?</span><h1 className="display">A GENTE QUER<br/>OUVIR VOCÊ.</h1></section><section className="contact-layout"><div><h2 className="display">ENTRE NO MOVIMENTO.</h2><p>Dúvidas sobre uma linha, pontos de venda ou uma ideia para compartilhar? Fale com a Moving.</p><a className="text-link" href={'mailto:'+site.email}>{site.email}<Arrow/></a><p>{site.company}<br/>CNPJ {site.cnpj}</p><p>{site.address}</p><div>{site.social.slice(0,2).map(s=><p key={s.name}><a className="text-link" href={s.url} target="_blank" rel="noopener noreferrer">{s.name}<Arrow/></a></p>)}</div></div><ContactForm/></section></main>;
 return <main id="main" className="page-enter"><section className="internal-hero"><span className="eyebrow">Moving · Informações</span><h1 className="display">{p.title}</h1></section><article className="legal-body">{slug==='como-comprar'?<><h2>Escolha seu ritmo e seu sabor</h2><ol><li>Acesse o catálogo e encontre uma linha Moving.</li><li>Escolha o sabor e confira as informações do produto.</li><li>Use o botão de compra para acessar o anúncio vinculado no site oficial.</li><li>Confira preço, quantidade do kit, frete, prazo e disponibilidade no canal de venda antes de concluir.</li></ol><h2>Quando não há um link de compra</h2><p>Entre em contato com a Moving para consultar a disponibilidade. O catálogo não processa pagamentos.</p><p>Os links podem direcionar a unidades ou kits. Confira a descrição do anúncio.</p><MagneticButton href="/produtos">Escolher minha Moving</MagneticButton></>:slug==='politicas-de-cookies'?<><div className="review-note"><strong>Política em revisão pela marca.</strong><p>A redação final será ajustada às integrações utilizadas na versão publicada.</p></div><h2>Preferência da abertura</h2><p>Esta experiência usa armazenamento de sessão no navegador para lembrar que você já assistiu à abertura. Essa preferência evita repetir o vídeo durante a mesma sessão.</p><h2>Conteúdo e serviços externos</h2><p>As fotografias e fontes são servidas pelo próprio site. Ao abrir um canal de compra ou perfil social, passam a valer as políticas daquele serviço.</p><p>Nenhum recurso de publicidade ou análise de comportamento foi integrado ao código desta experiência. Serviços da plataforma de hospedagem podem utilizar seus próprios recursos de funcionamento.</p><h2>Fale com a Moving</h2><p>Para dúvidas, escreva para <a href={'mailto:'+site.email}>{site.email}</a>.</p></>:<><div className="review-note"><strong>Documento em revisão pela marca.</strong><p>A política definitiva desta experiência será validada conforme os serviços conectados aos formulários.</p></div><h2>Quem é a Moving</h2><p>{site.company}, CNPJ {site.cnpj}. {site.address}.</p><h2>Contato e newsletter</h2><p>O formulário de contato solicita nome, e-mail e mensagem. A newsletter solicita e-mail e confirmação de interesse. Os formulários informam quando o serviço de envio não está disponível; uma tentativa sem confirmação não representa inscrição ou mensagem recebida.</p><h2>Política oficial</h2><p>A Moving mantém sua política no site oficial. <a href={site.officialPrivacy} target="_blank" rel="noopener noreferrer">Consultar o documento atual</a>.</p><h2>Solicitações sobre seus dados</h2><p>Use o canal informado pela Moving: <a href={'mailto:'+site.email}>{site.email}</a>.</p></>}</article></main>;
}
