import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import articles from '@/data/articles.json';
import {site} from '@/data/site';
import {Newsletter} from '@/components/moving/conversion';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)return {title:'Conteúdo não encontrado'};return {title:a.title,description:a.excerpt,alternates:{canonical:'/blog/'+slug},openGraph:{type:'article',title:a.title,description:a.excerpt,publishedTime:a.date,authors:[a.author]}};}
export default async function Page({params}:Props){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <main id="main" className="page-enter"><header className="article-heading"><nav className="breadcrumb" aria-label="Você está aqui"><Link href="/">Início</Link><span>/</span><Link href="/blog">Conteúdos</Link></nav><span className="eyebrow">{a.category}</span><h1 className="display">{a.title}</h1><div className="article-byline"><span>Por {a.author}</span><time dateTime={a.date}>{new Date(a.date+'T12:00:00').toLocaleDateString('pt-BR')}</time></div></header>{a.image&&<img className="article-cover" src={a.image} alt={a.title} width="1200" height="700" fetchPriority="high"/>}<article className="article-body"><div dangerouslySetInnerHTML={{__html:a.html}}/><div className="article-source">Conteúdo publicado pela Moving. <a className="text-link" href={a.source} target="_blank" rel="noopener noreferrer">Consultar publicação original ↗</a></div><Link className="text-link" href="/blog">← Voltar aos conteúdos</Link></article><Newsletter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.excerpt,datePublished:a.date,author:{'@type':'Organization',name:a.author},publisher:{'@type':'Organization',name:'Moving'},image:a.image?site.origin+a.image:undefined,mainEntityOfPage:site.origin+'/blog/'+a.slug})}}/></main>;}
